const COMUNI_REGIONI = {
  "ROMA":"Lazio",
  "MILANO":"Lombardia",
  "NAPOLI":"Campania",
  "TORINO":"Piemonte",
  "PALERMO":"Sicilia",
  "BARI":"Puglia",
  "CAGLIARI":"Sardegna",
  "BOLOGNA":"Emilia-Romagna",
  "FIRENZE":"Toscana",
  "GENOVA":"Liguria",
  "VENEZIA":"Veneto",
  "CATANZARO":"Calabria",
  "COSENZA":"Calabria",
  "CROTONE":"Calabria",
  "REGGIO CALABRIA":"Calabria",
  "VIBO VALENTIA":"Calabria",
  "SALERNO":"Campania",
  "ISOLA DI CAPO RIZZUTO":"Calabria",
  "MERCATO SARACENO":"Emilia-Romagna"
};
